import sys
import Main
from PyQt5 import QtCore, QtGui, QtWidgets


class GUIMainWindow(object):

    def __init__(self):
        self.engine_list = ['网易云音乐', 'QQ音乐', '酷狗音乐', '酷我音乐', '虾米音乐', '咪咕音乐']
        self.setup_ui(QtWidgets.QMainWindow())

    def setup_ui(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(939, 730)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(size_policy)
        self.centralwidget = QtWidgets.QWidget(main_window)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(size_policy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(1)
        size_policy.setVerticalStretch(1)
        size_policy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(size_policy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.search_tab = QtWidgets.QWidget()
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.search_tab.sizePolicy().hasHeightForWidth())
        self.search_tab.setSizePolicy(size_policy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.search_tab.setFont(font)
        self.search_tab.setObjectName("search_tab")
        self.search_page = QtWidgets.QGridLayout(self.search_tab)
        self.search_page.setContentsMargins(10, 10, 10, 10)
        self.search_page.setObjectName("search_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.engine_switch = QtWidgets.QComboBox(self.search_tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(1)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.engine_switch.sizePolicy().hasHeightForWidth())
        self.engine_switch.setSizePolicy(size_policy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.engine_switch.setFont(font)
        self.engine_switch.setObjectName("engine_switch")
        self.engine_switch.addItems(self.engine_list)
        self.horizontalLayout.addWidget(self.engine_switch)
        self.search_name = QtWidgets.QLineEdit(self.search_tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(6)
        size_policy.setVerticalStretch(1)
        size_policy.setHeightForWidth(self.search_name.sizePolicy().hasHeightForWidth())
        self.search_name.setSizePolicy(size_policy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.search_name.setFont(font)
        self.search_name.setObjectName("search_name")
        self.horizontalLayout.addWidget(self.search_name)
        self.search_button = QtWidgets.QPushButton(self.search_tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(1)
        size_policy.setVerticalStretch(1)
        size_policy.setHeightForWidth(self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(size_policy)
        self.search_button.setText('搜索')
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.search_button.setFont(font)
        self.search_button.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.search_button)
        self.search_page.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.search_result = QtWidgets.QTableView(self.search_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.search_result.setFont(font)
        self.search_result.setObjectName("search_result")
        self.search_page.addWidget(self.search_result, 1, 0, 1, 1)
        self.tabWidget.addTab(self.search_tab, "搜索")
        self.option_page = QtWidgets.QWidget()
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.option_page.sizePolicy().hasHeightForWidth())
        self.option_page.setSizePolicy(size_policy)
        self.option_page.setObjectName("option_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.option_page)
        self.gridLayout_3.setContentsMargins(100, 0, 100, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_1 = QtWidgets.QLabel(self.option_page)
        self.label_1.setObjectName("label_1")
        self.label_1.setText('下载地址：')
        self.gridLayout_3.addWidget(self.label_1, 0, 0, 1, 1)
        self.filepath = QtWidgets.QLineEdit(self.option_page)
        self.filepath.setObjectName("filepath")
        self.gridLayout_3.addWidget(self.filepath, 0, 1, 1, 2)
        self.custom_filepath = QtWidgets.QToolButton(self.option_page)
        self.custom_filepath.setObjectName("custom_filepath")
        self.custom_filepath.setText('...')
        self.gridLayout_3.addWidget(self.custom_filepath, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.option_page)
        self.label_2.setObjectName("label_2")
        self.label_2.setText('命名格式：')
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(self.option_page)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_1.setText('歌曲名-歌手')
        self.filename = QtWidgets.QButtonGroup(main_window)
        self.filename.setObjectName("filename")
        self.filename.addButton(self.radioButton_1)
        self.gridLayout_3.addWidget(self.radioButton_1, 1, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.option_page)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setText('歌手-歌曲名')
        self.filename.addButton(self.radioButton_2)
        self.gridLayout_3.addWidget(self.radioButton_2, 1, 2, 1, 2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.option_page)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.setText('歌曲名')
        self.filename.addButton(self.radioButton_3)
        self.gridLayout_3.addWidget(self.radioButton_3, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.option_page)
        self.label_3.setObjectName("label_3")
        self.label_3.setText('歌词格式：')
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.option_page)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.setText('.lrc')
        self.lyric_format = QtWidgets.QButtonGroup(main_window)
        self.lyric_format.setObjectName("lyric_format")
        self.lyric_format.addButton(self.radioButton_4)
        self.gridLayout_3.addWidget(self.radioButton_4, 2, 1, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.option_page)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_5.setText('.txt')
        self.lyric_format.addButton(self.radioButton_5)
        self.gridLayout_3.addWidget(self.radioButton_5, 2, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.option_page)
        self.label_4.setObjectName("label_4")
        self.label_4.setText('软件关闭：')
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.option_page)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_6.setText('退出到托盘')
        self.exit_mode = QtWidgets.QButtonGroup(main_window)
        self.exit_mode.setObjectName("exit_mode")
        self.exit_mode.addButton(self.radioButton_6)
        self.gridLayout_3.addWidget(self.radioButton_6, 3, 1, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.option_page)
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_7.setText('关闭软件')
        self.exit_mode.addButton(self.radioButton_7)
        self.gridLayout_3.addWidget(self.radioButton_7, 3, 2, 1, 2)
        self.tabWidget.addTab(self.option_page, "设置")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.show()
        sys.exit(app.exec_())


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    run = GUIMainWindow()
